"""
Prometheus Metrics & Observability Collector
─────────────────────────────────────────────
Exposes standard Prometheus-compatible telemetry metrics (/metrics)
without requiring heavy external monitoring daemons.
"""

import time
import threading
from collections import defaultdict
from typing import Dict, List, Tuple


class MetricsCollector:
    _instance = None
    _lock = threading.Lock()

    def __new__(cls):
        with cls._lock:
            if cls._instance is None:
                cls._instance = super(MetricsCollector, cls).__new__(cls)
                cls._instance._init_metrics()
            return cls._instance

    def _init_metrics(self):
        self.request_counts: Dict[Tuple[str, str, int], int] = defaultdict(int)
        self.request_durations: Dict[str, List[float]] = defaultdict(list)
        self.documents_processed: Dict[Tuple[str, str], int] = defaultdict(int)
        self.retrieval_durations: List[float] = []
        self.llm_token_counts: Dict[str, int] = defaultdict(int)
        self.active_sessions: int = 0
        self.start_time: float = time.time()

    def record_request(self, method: str, path: str, status_code: int, duration_sec: float):
        with self._lock:
            # Group paths to avoid unbounded cardinality
            clean_path = path.split("?")[0]
            if clean_path.startswith("/api/sessions/") and len(clean_path.split("/")) > 3:
                sub = clean_path.split("/")[3]
                clean_path = f"/api/sessions/:id/{sub}"
            elif clean_path.startswith("/api/documents/"):
                clean_path = "/api/documents/:id"
            elif clean_path.startswith("/api/memory/"):
                clean_path = "/api/memory/:id"

            self.request_counts[(method, clean_path, status_code)] += 1
            # Keep last 500 samples for duration percentiles
            self.request_durations[clean_path].append(duration_sec)
            if len(self.request_durations[clean_path]) > 500:
                self.request_durations[clean_path].pop(0)

    def record_document_processed(self, file_type: str, status: str):
        with self._lock:
            self.documents_processed[(file_type, status)] += 1

    def record_retrieval(self, duration_sec: float):
        with self._lock:
            self.retrieval_durations.append(duration_sec)
            if len(self.retrieval_durations) > 500:
                self.retrieval_durations.pop(0)

    def record_tokens(self, provider: str, token_count: int):
        with self._lock:
            self.llm_token_counts[provider] += token_count

    def generate_prometheus_text(self) -> str:
        """Generate official Prometheus text format exposition."""
        lines = []
        lines.append("# HELP docmind_uptime_seconds Total runtime of the DocMind service.")
        lines.append("# TYPE docmind_uptime_seconds counter")
        lines.append(f"docmind_uptime_seconds {time.time() - self.start_time:.2f}")

        lines.append("# HELP docmind_http_requests_total Total number of HTTP requests processed.")
        lines.append("# TYPE docmind_http_requests_total counter")
        for (method, path, status), count in self.request_counts.items():
            lines.append(f'docmind_http_requests_total{{method="{method}",path="{path}",status="{status}"}} {count}')

        lines.append("# HELP docmind_documents_processed_total Total documents ingested and processed.")
        lines.append("# TYPE docmind_documents_processed_total counter")
        for (file_type, status), count in self.documents_processed.items():
            lines.append(f'docmind_documents_processed_total{{file_type="{file_type}",status="{status}"}} {count}')

        lines.append("# HELP docmind_llm_tokens_generated_total Total LLM output tokens generated by provider.")
        lines.append("# TYPE docmind_llm_tokens_generated_total counter")
        for provider, tokens in self.llm_token_counts.items():
            lines.append(f'docmind_llm_tokens_generated_total{{provider="{provider}"}} {tokens}')

        if self.retrieval_durations:
            avg_ret = sum(self.retrieval_durations) / len(self.retrieval_durations)
            lines.append("# HELP docmind_rag_retrieval_duration_seconds Average RAG hybrid search latency.")
            lines.append("# TYPE docmind_rag_retrieval_duration_seconds gauge")
            lines.append(f"docmind_rag_retrieval_duration_seconds {avg_ret:.4f}")

        return "\n".join(lines) + "\n"


metrics = MetricsCollector()
